language: node_js
node_js:
    - "4.4.0"
    - "6.3.0"
before_install: 
    - npm install mocha -g
    - npm install coveralls -g
    - npm install mocha-lcov-reporter -g
script: npm run-script coveralls
